name: Tusk Test Runner
description: Run Tusk tests
author: Tusk

branding:
  icon: "code"
  color: "purple"

inputs:
  runId:
    description: "Tusk run ID"
    required: true
  tuskUrl:
    description: "Tusk server URL"
    required: true
  commitSha:
    description: "Commit SHA to checkout"
    required: true
  authToken:
    description: "Tusk server authentication token"
    required: true
  appDir:
    description: "App directory for the service, if there are multiple services in the repo"
    required: false
  testFramework:
    description: "Test framework used for the service"
    required: true
  testFileRegex:
    description: "Regex to match test files in the service"
    required: true
  testScript:
    description: "Test script to run"
    required: true
  lintScript:
    description: "Lint script to run"
    required: false
  coverageScript:
    description: "Coverage script to run"
    required: false
  pollingDuration:
    description: "How long to poll for commands (in seconds)"
    required: false
    default: "7200"
  pollingInterval:
    description: "How often to poll for commands (in seconds)"
    required: false
    default: "2"
  maxConcurrency:
    description: "Maximum number of commands to run concurrently"
    required: false
  runnerIndex:
    description: "Runner index"
    required: false

runs:
  using: node20
  main: dist/index.js
