name: Tusk Test Runner
description: Run Tusk tests
author: Tusk

branding:
  icon: "code"
  color: "purple"

inputs:
  runId:
    description: "Tusk run ID"
    required: true
  tuskUrl:
    description: "Tusk server URL"
    required: true
  authToken:
    description: "Tusk server authentication token"
    required: true
  testScript:
    description: "Test script to run"
    required: true
  lintScript:
    description: "Lint script to run"
    required: true
  coverageScript:
    description: "Coverage script to run"
    required: false
  pollingDuration:
    description: "How long to poll for commands (in seconds)"
    required: false
    default: "3600"
  pollingInterval:
    description: "How often to poll for commands (in seconds)"
    required: false
    default: "5"

runs:
  using: node20
  main: dist/index.js
